// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwCHbeFDe5q6slaOiJabAkF4C_WT1hQo',
    appId: '1:366847837897:web:092343edae680131986f18',
    messagingSenderId: '366847837897',
    projectId: 'quiz-a1bad',
    authDomain: 'quiz-a1bad.firebaseapp.com',
    storageBucket: 'quiz-a1bad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqEWYo6e2GumdBTOkZneGv3rUpQWyji4U',
    appId: '1:366847837897:android:bb9200c4aafee032986f18',
    messagingSenderId: '366847837897',
    projectId: 'quiz-a1bad',
    storageBucket: 'quiz-a1bad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_MVhyKc9eC0wRaPlDPFrH1NVQLGRHHE',
    appId: '1:366847837897:ios:a1908025078811cf986f18',
    messagingSenderId: '366847837897',
    projectId: 'quiz-a1bad',
    storageBucket: 'quiz-a1bad.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
